spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://mysqladdress?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  redis:
    host: redisadd
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
server:
  servlet:
    context-path: /sell
  port: 8081
logging:
  level:
    com.example.demo.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml