spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xxxxx
    password: xxxxxx
    url: jdbc:mysql://xxxxxx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
server:
  servlet:
    context-path: /xxxxx
logging:
  level:
    com.example.demo.DAO.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml